name: Scheduled
on:
  schedule:
    - cron: '0 6 * * 1'  # every Monday at 06:00 UTC
  workflow_dispatch:
jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container: ghcr.io/geocompx/suggests:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
